
FROM python:3.13-slim


WORKDIR /app


COPY requirements.txt .
COPY bot.py .


RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


ENV TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

# 6. Команда запуска бота
CMD ["python", "bot.py"]
